server:
  port: 8020
spring:
 application:
   name: order-service
 cloud:
   nacos:
     service-add: 127.0.0.1:8848
     discovery:
       username: nacos
       password: nacos
       namespace: public
